import os

from dotenv import load_dotenv

load_dotenv()

APPWRITE_PROJECT_ID = os.environ["APPWRITE_PROJECT_ID"]
APPWRITE_API_KEY = os.environ["APPWRITE_API_KEY"]
APPWRITE_DATABASE_ID = os.environ["APPWRITE_DATABASE_ID"]
USERS_COLLECTION_ID = os.environ.get("APPWRITE_USERS_COLLECTION_ID")
RECIPES_COLLECTION_ID = os.environ.get("APPWRITE_RECIPES_COLLECTION_ID")
INTERACTIONS_COLLECTION_ID = os.environ.get("APPWRITE_INTERACTIONS_COLLECTION_ID")
POSTS_COLLECTION_ID = os.environ.get("APPWRITE_POSTS_COLLECTION_ID")
COMMUNITIES_COLLECTION_ID = os.environ.get("APPWRITE_COMMUNITIES_COLLECTION_ID")
RECOMMENDATION_DATA_COLLECTION_ID = os.environ.get(
    "APPWRITE_RECOMMENDATION_DATA_COLLECTION_ID"
)
